# Generated by Django 5.2.6 on 2025-09-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
