# Generated by Django 5.2.6 on 2025-09-25 10:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('about', ckeditor.fields.RichTextField()),
                ('about_en', ckeditor.fields.RichTextField(null=True)),
                ('about_uz', ckeditor.fields.RichTextField(null=True)),
                ('about_ru', ckeditor.fields.RichTextField(null=True)),
                ('img', models.ImageField(upload_to='categories/')),
            ],
        ),
    ]
