# Generated by Django 5.2.6 on 2025-09-25 12:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_banner_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Category Item',
                'verbose_name_plural': 'Category Items',
            },
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_uz', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('categoryItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoryitem')),
            ],
            options={
                'verbose_name': 'Item Info',
                'verbose_name_plural': 'Item Infos',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='item_images/')),
                ('itemInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.iteminfo')),
            ],
        ),
    ]
