# Generated by Django 5.2.6 on 2025-09-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_categoryitem_iteminfo_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='main.category'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='itemInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='main.iteminfo'),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='categoryItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_infos', to='main.categoryitem'),
        ),
    ]
