# Generated by Django 5.2.6 on 2025-09-25 13:06

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_categoryitem_category_alter_itemimage_iteminfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='itemInfo',
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemimage',
            name='categoryItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='main.categoryitem'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemInfo',
        ),
    ]
