# Generated by Django 5.2.6 on 2025-09-25 13:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_itemimage_iteminfo_categoryitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitem',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
