# Generated by Django 5.2.6 on 2025-09-25 13:52

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_categoryitem_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('description_uz', ckeditor.fields.RichTextField(null=True)),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('img', models.ImageField(upload_to='last_items/')),
                ('categoryItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_items', to='main.categoryitem')),
            ],
            options={
                'verbose_name': 'Last Item',
                'verbose_name_plural': 'Last Items',
            },
        ),
    ]
