# Generated by Django 5.2.6 on 2025-09-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_lastitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'verbose_name': 'Item Image', 'verbose_name_plural': 'Item Images'},
        ),
        migrations.RemoveField(
            model_name='lastitem',
            name='img',
        ),
        migrations.CreateModel(
            name='LastItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='last_item_images/')),
                ('lastItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_item_images', to='main.lastitem')),
            ],
            options={
                'verbose_name': 'Last Item Image',
                'verbose_name_plural': 'Last Item Images',
            },
        ),
    ]
