# Generated by Django 5.2.6 on 2025-09-25 14:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_itemimage_options_remove_lastitem_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryitem',
            old_name='description',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='categoryitem',
            old_name='description_en',
            new_name='about_en',
        ),
        migrations.RenameField(
            model_name='categoryitem',
            old_name='description_ru',
            new_name='about_ru',
        ),
        migrations.RenameField(
            model_name='categoryitem',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='categoryitem',
            old_name='title_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='categoryitem',
            old_name='title_ru',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='categoryitem',
            old_name='title_uz',
            new_name='name_uz',
        ),
        migrations.RemoveField(
            model_name='categoryitem',
            name='description_uz',
        ),
        migrations.AddField(
            model_name='categoryitem',
            name='about_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
